version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=corsi_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
    - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data1
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"